// SOME IMP NOTES :
// 1. ITS ALWAYS A GOOD PRACTICE TO MAKE ANOTHER FOLDER TO WRITE ALL THE COMPONENTS
// 2. COMPONENTS NAME MUST BE START WITH CAP LETTER ELSE REACT THINK ITS AN HTML TAG (NO HTML TAGS START WITH CAP LETTER SO ITS USED TO DIFFERENTIATE)
// 3. ONLY ONE EXPORT DEFAULT ALLOWED
// 4. N NUMBER OF NAMED EXPORTS ARE ALLOWED
// 5. A COMPONENT CAN RUN ANOTHER COMPONENT INSIDE IT BUT GENERALLY ITS CONSIDER BAD PRACTICES AND CAN BRING BUGS IN CODE

import LoadingPage from "./components/Loadingpage";

// 6. ITS PREFERRED TO WRITE THE PARENT COMPONENTS ON BOTTOM.
export default function App(){
  return (
    <LoadingPage/>
  )
}
